; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 5
; RUN: llc -mtriple=aarch64-linux-gnu < %s | FileCheck %s

; https://github.com/llvm/llvm-project/issues/222095
; When the same constant magnitude is needed once added and once subtracted,
; and that magnitude doesn't fit as a direct immediate on this target, the
; positive form should be materialized once and shared (via a plain `sub`)
; rather than also materializing an unrelated negated constant.

define i32 @add_sub_shared_const_i32(i32 %a, i32 %b) {
; CHECK-LABEL: add_sub_shared_const_i32:
; CHECK:       // %bb.0:
; CHECK-NEXT:    str x30, [sp, #-16]! // 8-byte Folded Spill
; CHECK-NEXT:    .cfi_def_cfa_offset 16
; CHECK-NEXT:    .cfi_offset w30, -16
; CHECK-NEXT:    mov w8, #4097 // =0x1001
; CHECK-NEXT:    sub w1, w1, w8
; CHECK-NEXT:    add w0, w0, w8
; CHECK-NEXT:    bl use32
; CHECK-NEXT:    ldr x30, [sp], #16 // 8-byte Folded Reload
; CHECK-NEXT:    ret
  %add = add i32 %a, 4097
  %sub = add i32 %b, -4097
  %r = call i32 @use32(i32 %add, i32 %sub)
  ret i32 %r
}
declare i32 @use32(i32, i32)

define i64 @add_sub_shared_const_i64(i64 %a, i64 %b) {
; CHECK-LABEL: add_sub_shared_const_i64:
; CHECK:       // %bb.0:
; CHECK-NEXT:    str x30, [sp, #-16]! // 8-byte Folded Spill
; CHECK-NEXT:    .cfi_def_cfa_offset 16
; CHECK-NEXT:    .cfi_offset w30, -16
; CHECK-NEXT:    mov x8, #4097 // =0x1001
; CHECK-NEXT:    mov w9, #4097 // =0x1001
; CHECK-NEXT:    sub x1, x1, x8
; CHECK-NEXT:    add x0, x0, x9
; CHECK-NEXT:    bl use64
; CHECK-NEXT:    ldr x30, [sp], #16 // 8-byte Folded Reload
; CHECK-NEXT:    ret
  %add = add i64 %a, 4097
  %sub = add i64 %b, -4097
  %r = call i64 @use64(i64 %add, i64 %sub)
  ret i64 %r
}
declare i64 @use64(i64, i64)

; The same tie-break must not fire when the other operand is a multiply:
; madd can fold the constant directly into its accumulator, which is
; strictly better than materializing the positive magnitude and using a
; separate sub. This is a regression guard for that specific interaction.
define i64 @add_neg_tied_const_does_not_break_madd(i64 %a) {
; CHECK-LABEL: add_neg_tied_const_does_not_break_madd:
; CHECK:       // %bb.0:
; CHECK-NEXT:    mov w8, #37 // =0x25
; CHECK-NEXT:    mov x9, #-32888 // =0xffffffffffff7f88
; CHECK-NEXT:    movk x9, #65518, lsl #16
; CHECK-NEXT:    madd x0, x0, x8, x9
; CHECK-NEXT:    ret
  %tmp0 = add i64 %a, -31000
  %tmp1 = mul i64 %tmp0, 37
  ret i64 %tmp1
}

; Self-negating edge case: for i32, -2147483648 (INT_MIN) negated wraps back
; to itself, so there is no positive magnitude to converge on. The tie-break
; must not fire here, or it would needlessly flip the opcode for no benefit.
define i32 @add_self_negating_const(i32 %a) {
; CHECK-LABEL: add_self_negating_const:
; CHECK:       // %bb.0:
; CHECK-NEXT:    mov w8, #-2147483648 // =0x80000000
; CHECK-NEXT:    add w0, w0, w8
; CHECK-NEXT:    ret
  %add = add i32 %a, -2147483648
  ret i32 %add
}
